credentials:
  usernames:
    willbankmmm:
      email: geethu4444@gmail.com
      name: Geetakrishna
      password: '$2b$12$r.KJDzrp6kFErWwh/n7vh.eSvXNU60HBDjrQrNQqkqOH8KSlVacMu'
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - geethu4444@gmail.com